### ISSUE TITLE
Pod Doesn't work out of box.

### ISSUE THREAD

**Issue by defal7** [cemolcay/PullToRefreshCoreText#3]
Needs to have main.m, viewcontroller.h/m deleted, other wise will clash and give linker errors on most builds.

**Comment by henryfisherhardy** [comment]
Also, mask.png needs to be included in pod.

**Comment by cemolcay** [comment]
yes you're right. i fixed it. 
you can use `pod 'PullToRefreshCoreText', '~> 0.2'` now.
